In [1]:
import numpy as np

### Q.NO.1

In [2]:
arr = np.array([ 0 , 1 , 2 , 3 , 4 , 5 ])
arr

array([0, 1, 2, 3, 4, 5])

In [3]:
arr.dtype

dtype('int64')

### Q.NO.2

In [4]:
arr = np.array([1.5 , 2.6 ,3.7])
arr

array([1.5, 2.6, 3.7])

In [5]:
arr.dtype  ## yes the data type of arr is float 64

dtype('float64')

### Q.NO. 3

In [6]:
arr = np.array([ 12 , 56 , 87 ] , dtype = np.complex128)
arr

array([12.+0.j, 56.+0.j, 87.+0.j])

In [7]:
arr.dtype

dtype('complex128')

### Q.NO.4

In [8]:
arr = np.array([45 , 9 , 85 , 9 , 6 , 5 , 2 ])
arr

array([45,  9, 85,  9,  6,  5,  2])

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr1 = arr.astype('float32')
arr1

array([45.,  9., 85.,  9.,  6.,  5.,  2.], dtype=float32)

### Q.NO.5

In [11]:
arr = np.array([ 1.23456789, 2.3456789, 3.456789, 4.56789 ] ,dtype = np.float64)
arr

array([1.23456789, 2.3456789 , 3.456789  , 4.56789   ])

In [12]:
arr1 = arr.astype('float32')
arr1

array([1.2345679, 2.3456788, 3.456789 , 4.56789  ], dtype=float32)

### Q.NO.6

In [13]:
arr = np.array([1,2,34,56,7,88,45])
arr

array([ 1,  2, 34, 56,  7, 88, 45])

In [14]:
def array_attributes(arr):
    dt = arr.dtype
    sh = np.shape(arr)
    size = np.size(arr)
    
    return dt,sh,size

array_attributes(arr)

(dtype('int64'), (7,), 7)

### Q.NO.7

In [15]:
arr = np.array([1 , 54 , 67 , 89 , 32 ])
arr

array([ 1, 54, 67, 89, 32])

In [16]:
def array_dimension(arr):

    return np.ndim(arr)
array_dimension(arr)

1

### Q.No.8

In [17]:
arr = np.array(['pw' , 'skills' , 'data' , 'science'])
arr

array(['pw', 'skills', 'data', 'science'], dtype='<U7')

In [18]:
def item_size_info(arr):

    print("item size : " , arr.itemsize)  ## here we get the item size of array
    print("total size : " , arr.nbytes)

item_size_info(arr)

item size :  28
total size :  112


### Q.NO.9

In [19]:

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
array_strides(arr)

(24, 8)

In [20]:
## alter method
array_strides = np.array([[1, 2, 3], [4, 5, 6]])
array_strides

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array_strides.strides   ##here 24 represent that each row consists of 24 bytes 
## 8 represents the number of bytes to move from one column to another in the same row



(24, 8)

### Q.NO 10

In [22]:
shape_stride_relationship = np.array([[1, 2, 3, 7], [4, 5, 6 , 8]])
shape_stride_relationship

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [23]:
shape_stride_relationship.shape

(2, 4)

In [24]:
shape_stride_relationship.strides

(32, 8)

In [25]:
## altermethod

def shape_stride_relationship(a):
    a = np.array([[1, 2, 3, 7], [4, 5, 6 , 8]])
    stride = a.strides
    shape = a.shape
    
    return stride , shape
a = np.array([[1, 2, 3, 7], [4, 5, 6 , 8]])
shape_stride_relationship(a)

((32, 8), (2, 4))

### Q.NO.11 

In [26]:
create_zeroes_array = np.zeros(4)
create_zeroes_array 

array([0., 0., 0., 0.])

In [28]:
## otherway

def create_zeroes_array(n):
    return np.zeros(n)


n = int(input("enter the integer value: "))

create_zeroes_array(n)

enter the integer value:  4


array([0., 0., 0., 0.])

### Q.NO.12

In [29]:
create_ones_matrix = np.ones((3,4))
create_ones_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
## alter method

def create_ones_matrix(arr):
    arr = np.ones ((rows ,columns))
    return arr
        
rows = int(input("please enter the integer value of rows :"))
columns = int(input("please enter the integer value of columns: "))

create_ones_matrix(arr)

please enter the integer value of rows : 4
please enter the integer value of columns:  4


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Q.NO.13

In [31]:
def generate_range_array(a,b,c):
    return np.arange(a,b,c)
    

a = 0      ## start 
b = 20     ## stop(exclusive)
c = 2      ## step

generate_range_array(a,b,c)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
## alter method

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Q.NO.14

In [33]:
def generate_linear_space( start , stop , num):
    return np.arange(start , stop+num , num)

start = 1.5
stop = 9.5
num = 1

generate_linear_space( start , stop , num)


array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

### Q.NO.15

In [34]:
def create_identity_matrix(n):
    return np.eye((n))

n= int(input("Enter the integer value:"))

create_identity_matrix(n)

Enter the integer value: 4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Q.NO.16

In [35]:
def py_np(list1):
    return np.asarray(list1)

list1 = [ 12 , 44 , 67 , 43 , 6 , 7 ]

py_np(list1)

array([12, 44, 67, 43,  6,  7])

### Q.NO.17

In [36]:
arr = np.array([ 23 , 56 , 78 , 54 , 32 ])
arr

array([23, 56, 78, 54, 32])

In [98]:
new_arr = arr.view(dtype = np.int32)
new_arr

array([23,  0, 56,  0, 78,  0, 54,  0, 32,  0], dtype=int32)

### Q.NO.18

In [37]:
def concat(arr1 , arr2 ):
    return np.concatenate((arr1 ,arr2) , axis = 0)

arr1 = np.array(['hello' , 'world' , 'good' ])
arr2 = np.array(['work' , 'done' , 'excellent'])

concat(arr1 , arr2)

array(['hello', 'world', 'good', 'work', 'done', 'excellent'], dtype='<U9')

### Q.NO. 19

In [38]:
arr1 = np.array([[1,2,34,21],[2,5,7,9],[5,7,3,6]])
arr2 = np.array([[1],
                 [5],
                 [3]])
                
np.concatenate((arr1 , arr2 ), axis =1)
                

array([[ 1,  2, 34, 21,  1],
       [ 2,  5,  7,  9,  5],
       [ 5,  7,  3,  6,  3]])

### Q.NO.20

In [39]:
arr1 = np.array([[1,2,3,4] , [6,8,9,7]])
arr2 = np.array([[4,6,2,7] , [34,8,7,23]])

np.vstack((arr1 , arr2))

array([[ 1,  2,  3,  4],
       [ 6,  8,  9,  7],
       [ 4,  6,  2,  7],
       [34,  8,  7, 23]])

### Q.NO.21

In [40]:
def array_range(arr1):
    arr1 = np.arange(start,stop+1 , step)
    
    return arr1

start = 1
stop = 21
step = 2

array_range(arr1)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

### Q.NO.22

In [41]:
def equally_spaced(arr):
    arr1 = np.linspace(0,1,10)  ## as linspace gives us equally spaced values
    
    return arr1

equally_spaced(arr1)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Q.NO.23

In [42]:
def log_spaced(arr):
    
    arr1 = np.logspace(0,3,5)  ## evenly spaced log values between 1 and 1000
    
    return arr1

log_spaced(arr1)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

### Q.NO.24

In [43]:
arr24 = np.random.randint(1,100,size = (5,3))
arr24

array([[43, 81, 69],
       [15, 18, 16],
       [62, 51, 38],
       [54, 73, 44],
       [91, 93, 27]])

In [44]:
import pandas as pd

df = pd.DataFrame(arr24)
df

0   1   2
0  43  81  69
1  15  18  16
2  62  51  38
3  54  73  44
4  91  93  27

### Q.NO.25

In [45]:
data1 = {'A': [1, 2, 3, -4, 5],'B': [-1, 2, -3, 4, -5],'C': [5, 4, 3, 2, 1]}
df = pd.DataFrame(data1)
df


A  B  C
0  1 -1  5
1  2  2  4
2  3 -3  3
3 -4  4  2
4  5 -5  1

In [46]:
def pd_data():   ## dataframe after replacing negative values of column 'B' values
   
    data1 = {'A': [1, 2, 3, -4, 5],'B': [-1, 2, -3, 4, -5],'C': [5, 4, 3, 2, 1]}
    df = pd.DataFrame(data1)
    df['B'] = np.where(df['B']<0,0,df['B'])
    
    return df
    
pd_data()

A  B  C
0  1  0  5
1  2  2  4
2  3  0  3
3 -4  4  2
4  5  0  1

### Q.NO.26

In [47]:
arr = np.array([10 , 20 , 30 , 40 , 50])

arr[2]  ## 3rd element of the array

30

### Q.NO.27

In [48]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

arr_2d[1][2]

6

### Q.NO.28

In [49]:
arr = np.array([ 3 , 8 , 2 , 10 , 5 , 7 ])
cond = arr>5

cond

array([False,  True, False,  True, False,  True])

In [50]:
np.extract(cond , arr)

array([ 8, 10,  7])

### Q.NO.29

In [51]:
## extracting elements from index 2 to 5

arr = np.array([ 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 ])


arr[2:6]

array([3, 4, 5, 6])

### Q.NO.30

In [52]:
## extracting subarray

arr_2d = np.array([[ 1 , 2 , 3 ],
                   [ 4 , 5 , 6 ],
                   [ 7 , 8 , 9 ]])

arr_2d[0:2,[1,2]]

array([[2, 3],
       [5, 6]])

### Q.NO.31

In [53]:
arr_2d = np.array([[ 1 , 2 , 3 ],
                   [ 4 , 5 , 6 ],
                   [ 7 , 8 , 9 ]])

extracted_elem = arr_2d.flatten()
extracted_elem
## first we created a array and then flattened it to access the indices easily

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
indices_arr = np.array([ 3 , 4 , 6 , 0 , 1 , 2 , 5 , 7 , 8 ]) 
indices_arr
## created an array whose element will act as index to extract the  element from another array

array([3, 4, 6, 0, 1, 2, 5, 7, 8])

In [55]:
extracted_elem = arr_2d.flatten()[indices_arr]

print(extracted_elem.reshape(arr_2d.shape))  
## reshaped the array again in 2d array

[[4 5 7]
 [1 2 3]
 [6 8 9]]


### Q.NO. 32

In [56]:
arr = np.array([ 1 , 4 , 2 , 7 , 6 , 4 , 5 , 8 , 4 , 3 , 9 , 12 ])


## created a threshold 
threshold = 4

print(arr>threshold)

print("array after condition : " ,arr[arr>threshold])

[False False False  True  True False  True  True False False  True  True]
array after condition :  [ 7  6  5  8  9 12]


### Q.No.33

In [57]:
arr = np.array([[[1,2,3],
               [5,6,7],
               [9,4,3]],
                [[3,6,2],
                 [4,8,1],
                 [5,8,2]]])

print("array is : " ,arr)

## 3 arrays for extracting elements
dim_1 = np.array([0,1])
dim_2 = np.array([2,0])
dim_3 = np.array([1,2])

# extracting elements using 3 arrays as indices
extracted_elem = arr[dim_1 ,dim_2 , dim_3]

print("extracted elements are :  ",extracted_elem)

array is :  [[[1 2 3]
  [5 6 7]
  [9 4 3]]

 [[3 6 2]
  [4 8 1]
  [5 8 2]]]
extracted elements are :   [4 2]


### Q.NO.34

In [58]:
arr = np.random.randint(1,20 ,(4,5))

print("array is  :" ,arr)

cond_1 = arr >3       ## condition 1 is that all elements should be greater than 3
cond_2 = (arr%2 ==0)  ## condition 2 is that elements should be divisible by 2

np.logical_and(cond_1 , cond_2)   

## gets all the values in boolean 

array is  : [[11  5  1 17 14]
 [13  6  3 18  7]
 [ 7  2 14  1  2]
 [ 5  7  2 10 14]]


array([[False, False, False, False,  True],
       [False,  True, False,  True, False],
       [False, False,  True, False, False],
       [False, False, False,  True,  True]])

In [59]:
arr[np.logical_and(cond_1 , cond_2)]

array([14,  6, 18, 14, 10, 14])

### Q.NO.35

In [60]:
arr = np.random.randint(1,8,(4,4))

print("array is : "  ,arr)

## arrays giving row and column indices
row_indices = np.array([1,3,2])
col_indices = np.array([2,1,3])

## extracting elements using row and column indices

extracted_arr = arr[row_indices , col_indices]

print("extracted array is : ",extracted_arr)

array is :  [[4 3 2 3]
 [4 7 2 3]
 [6 7 4 1]
 [3 1 4 4]]
extracted array is :  [2 1 1]


### Q.NO.36

In [61]:
arr = np.random.randint(1,5,(3,3))

print("array is :", arr)

## adding scalar value of 5 to each element 

arr1 = arr + 5

print("after addition array is : ", arr1)


array is : [[4 2 1]
 [4 1 1]
 [1 2 1]]
after addition array is :  [[9 7 6]
 [9 6 6]
 [6 7 6]]


### Q.NO.37

In [62]:
arr1 = np.random.randint(1,10 ,(1,3))
arr2 = np.random.randint(1,10 ,(3,4))

print("array 1 is : ",arr1)
print("array 2 is : ",arr2)


##we need to transpose arr1 to match the shapes

arr1.T

print("transpose of arr1 : " ,arr1.T)
## multiplying by numpy broadcasting

print("final output is : " , arr1.T * arr2)

array 1 is :  [[8 6 4]]
array 2 is :  [[9 9 9 8]
 [6 8 6 8]
 [5 6 4 1]]
transpose of arr1 :  [[8]
 [6]
 [4]]
final output is :  [[72 72 72 64]
 [36 48 36 48]
 [20 24 16  4]]


### Q.NO.38

In [63]:
arr1 = np.array([1, 2, 3, 4])  # shape (4,)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # shape (4, 3)

## reshaping array to 1 row and 4 columns
arr1_new = arr1.reshape(1,4,1)
print("the new array 1 is :" , arr1_new)


print("adding using numpy broadcasting : " ,arr1_new + arr2)

the new array 1 is : [[[1]
  [2]
  [3]
  [4]]]
adding using numpy broadcasting :  [[[ 6  7  8]
  [10 11 12]
  [14 15 16]
  [18 19 20]]]


### Q.NO.39

In [64]:
## Creating random arrays

arr1 = np.random.randint(2,5,(3,1))
arr2 = np.random.randint(2,5,(1,3))

## printing the arrays

print("array1 is : " ,arr1)
print("array2 is : " ,arr2)
## adding arrays

arr1 + arr2

array1 is :  [[2]
 [4]
 [3]]
array2 is :  [[3 4 2]]


array([[5, 6, 4],
       [7, 8, 6],
       [6, 7, 5]])

### Q.NO.40

In [65]:
arr1 = np.random.randint(1,10 ,(2,3))
arr2 = np.random.randint(1,8 , (2,2))
print(arr1)
print(arr2)
arr2_new = arr2.reshape(2,2,1)  ## we reshaped the array to handle the shape incompatibilty

print ("reshaped array : " ,arr2_new)
print("After multiplication broadcasting : " ,arr1 * arr2_new)

[[1 4 3]
 [3 1 4]]
[[1 2]
 [7 7]]
reshaped array :  [[[1]
  [2]]

 [[7]
  [7]]]
After multiplication broadcasting :  [[[ 1  4  3]
  [ 6  2  8]]

 [[ 7 28 21]
  [21  7 28]]]


In [66]:
## ALTERNATE METHOD

arr1 = np.random.randint(1,10 ,(2,3))
arr2 = np.random.randint(1,8 , (2,2))
print(arr1)
print(arr2)
arr1_new = arr1.reshape(3,2)
arr1_new  @ arr2

[[9 3 8]
 [8 7 9]]
[[6 3]
 [4 3]]


array([[66, 36],
       [80, 48],
       [78, 48]])

### Q.NO.41


In [67]:
arr = np.array([[1,2,3] ,[4,5,6]])
np.mean(arr ,axis=0)  ## arithmetic mean column-wise

array([2.5, 3.5, 4.5])

### Q.NO.42


In [68]:
arr = np.array([[1,2,3] , [ 4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.max(arr , axis =1)  ## max gives the maximum values along axis

array([3, 6])

### Q.NO.43


In [70]:
arr = np.array([[1,2,3] ,[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.argmax(arr ,axis =0)   ## argmax gives the indices with max. value on axis

array([1, 1, 1])

### Q.NO.44

In [72]:
def moving_sum(arr, window_size):
    cumsum = np.cumsum(arr, axis=1)
    cumsum[:, window_size:] = cumsum[:, window_size:] - cumsum[:, :-window_size]
    return cumsum[:, window_size - 1:]

arr = np.array([[1, 2, 3], [4, 5, 6]])
window_size = 2
result = moving_sum(arr, window_size)
print(result)


[[ 3  5]
 [ 9 11]]


### Q.NO.45

In [73]:
arr = np.array([[ 2 , 4 , 6 ] , [ 3 , 5 , 7 ]])

arr

array([[2, 4, 6],
       [3, 5, 7]])

In [74]:
is_even=  np.all(arr%2 ==0 ,axis = 0)

is_even  ## since all the elements in each column are not even 

array([False, False, False])

### Q.NO.46

In [75]:
original_array = np.array([ 1 , 2 , 3 , 4 , 5 , 6 ])

new_array = original_array.reshape((2,3))  ## we have taken m as 2 and n = 3
new_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q.NO.47

In [76]:
input_matrix = np.array([[ 1 , 2 , 3 ] , [ 4, 5 , 6 ]])

flattened_array = input_matrix.flatten()

flattened_array

array([1, 2, 3, 4, 5, 6])

### Q.NO.48

In [77]:
array1 = np.array([[1,2] , [3,4]])
array2 = np.array([[5,6] , [7,8]])

xaxis = np.concatenate((array1 , array2), axis =0)

print("along rows : " ,xaxis)

yaxis = np.concatenate((array1 , array2) , axis = 1)

print("along column: " , yaxis)

along rows :  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
along column:  [[1 2 5 6]
 [3 4 7 8]]


### Q.NO.49

In [78]:
original_array = np.array([[1, 2 , 3] , [4 , 5 , 6 ] , [ 7 , 8 , 9]])

xaxis_split = np.split(original_array , 3 , axis =0)

print("splitting along rows : ")
for subarray in xaxis_split:   
    print(subarray)

yaxis_split =np.split(original_array , 3 , axis =1)

print("splitting along columns: ")
for subarray1 in yaxis_split:
    print(subarray1)

splitting along rows : 
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
splitting along columns: 
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


### Q.NO.50

In [79]:
original_array = np.array([1,2,3,4,5])

indices_to_insert = [2,4]

values_to_insert = [10 , 11]

indices_to_delete = [1,3]

## inserted the elements [10,11] at the indices [2,4]
new_array = np.insert(original_array , indices_to_insert , values_to_insert)
new_array   

array([ 1,  2, 10,  3,  4, 11,  5])

In [80]:
np.delete(new_array , indices_to_delete)   ## deleted the elements on the indices [1,3]

array([ 1, 10,  4, 11,  5])

### Q.NO.51

In [81]:
arr1 = np.random.randint(1,20 ,10)
arr2 = np.arange(1,11)

print(" array1 is : " , arr1)
print(" array2 is : " , arr2)

print("addition : " , arr1 + arr2)

 array1 is :  [15 10  1  1  1 13 12 17 12  4]
 array2 is :  [ 1  2  3  4  5  6  7  8  9 10]
addition :  [16 12  4  5  6 19 19 25 21 14]


### Q.NO.52

In [82]:
arr1 = np.arange(10 , 0 ,-1)
arr2 = arr1[::-1]                  ##reversed the arr1 to get arr2

print(" array1 is : " , arr1)
print(" array2 is : " , arr2)

arr1 - arr2  ## subtracting arr2 from arr1

 array1 is :  [10  9  8  7  6  5  4  3  2  1]
 array2 is :  [ 1  2  3  4  5  6  7  8  9 10]


array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

### Q.NO.53

In [83]:
arr1 = np.random.randint(2,9 ,(1,5))
arr2 = np.arange(1,6)

print("array 1 is : ", arr1)
print("array 2 is : ", arr2)

arr1 * arr2  ## multiplication of arrays


array 1 is :  [[7 4 4 6 7]]
array 2 is :  [1 2 3 4 5]


array([[ 7,  8, 12, 24, 35]])

### Q.NO.54

In [84]:
arr1 = np.arange(2,12,2)
arr2 = np.arange(1,6)
print("array 1 is :" ,arr1)
print("array 2 is : " ,arr2)

array 1 is : [ 2  4  6  8 10]
array 2 is :  [1 2 3 4 5]


In [85]:
arr1 / arr2

array([2., 2., 2., 2., 2.])

### Q.NO.55

In [86]:
arr1 = np.array([ 1 , 2 , 3 , 4 , 5 ])
arr2 = arr1[::-1]  ## reversing the arr1 

np.power(arr1 , arr2)  ## element wise exponentiation

array([ 1, 16, 27, 16,  5])

### Q.NO.56

In [87]:
arr = np.array(['hello' , 'world' , 'hello' , 'numpy' , 'hello'])

substring = 'hello'

count = 0

for i in arr:
    if i in substring:
        count += 1
    
print("The count of occurances of substring is: ", count )

The count of occurances of substring is:  3


### Q.NO.57

In [88]:
arr = np.array(['Hello' , 'World' , 'OpenAI' , 'GPT'])
arr

array(['Hello', 'World', 'OpenAI', 'GPT'], dtype='<U6')

In [89]:
np.array([char for s in arr for char in s if char.isupper()])

array(['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T'], dtype='<U1')

### Q.NO.58

In [90]:
arr = np.array(['apple' , 'banana' , 'grape' , 'pineapple'])
substring = 'apple'
replacement = 'pear'

arr1 = np.char.replace(arr , substring , replacement)
    
print(arr1)  ## replaced apple with pear


['pear' 'banana' 'grape' 'pinepear']


### Q.No.59

In [91]:
arr1 = np.array(['Hello' , 'World'])
arr2 = np.array(['Opem' , 'AI'])

In [92]:
np.concatenate((arr1,arr2))  ## concatenate function concatenates two arrays 

array(['Hello', 'World', 'Opem', 'AI'], dtype='<U5')

### Q.NO.60

In [93]:
arr = np.array(['apple' , 'banana' , 'grape' , 'pineapple'])
arr

array(['apple', 'banana', 'grape', 'pineapple'], dtype='<U9')

In [94]:
def longest_string(arr):
    max_length = max(len(i) for i in arr)  # first we will find the maximum length in the array
    longest_strings = [i for i in arr if len(i) == max_length]  # Find strings with maximum length
    return longest_strings
longest_string(arr)

['pineapple']

### Q.NO.61

In [98]:
dataset = np.random.randint(1,1000 , size =100)
data = np.sort(dataset)
data

array([ 29,  33,  42,  66,  76,  84,  93, 100, 109, 125, 139, 152, 153,
       156, 185, 197, 212, 213, 214, 221, 233, 234, 236, 276, 280, 290,
       303, 313, 315, 348, 371, 375, 377, 394, 401, 404, 406, 411, 423,
       431, 434, 457, 466, 478, 494, 496, 498, 498, 504, 506, 519, 534,
       535, 549, 552, 554, 567, 570, 571, 582, 617, 634, 639, 658, 659,
       664, 673, 695, 701, 719, 732, 742, 752, 756, 760, 779, 780, 787,
       790, 806, 817, 819, 828, 832, 853, 855, 856, 859, 871, 874, 882,
       886, 888, 902, 905, 917, 919, 929, 968, 974])

In [104]:
np.mean(data) ## mean of the array having 100 random integers

517.61

In [105]:
np.median(data)  ## median of array 

512.5

In [106]:
np.var(data)  ## gives variance of array

73775.79789999999

In [107]:
np.std(data)      ## gives standard deviation

271.6170059108965

### Q.NO.62

In [103]:
arr = np.random.randint(1,101 , size = 50)
arr1 = np.sort(arr)
arr1

array([ 3,  4,  8,  9, 10, 12, 13, 14, 17, 18, 19, 19, 25, 25, 28, 30, 31,
       32, 33, 36, 36, 36, 37, 37, 37, 38, 38, 39, 42, 47, 47, 48, 48, 54,
       63, 63, 69, 70, 73, 73, 77, 79, 79, 83, 84, 85, 86, 86, 89, 93])

In [108]:
percentile_25th = np.percentile(arr1 , 25)  ## gives the percentile
percentile_25th

25.0

In [109]:
percentile_75th = np.percentile(arr1 , 75)
percentile_75th

69.75

### Q.NO.63

In [110]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([15, 20, 36, 40, 55])

In [111]:
arr1

array([1, 2, 3, 4, 5])

In [112]:
arr2

array([15, 20, 36, 40, 55])

In [113]:
np.corrcoef(arr1, arr2)  ## np.corrcoef gives the correlational coeeficient of arrays

array([[1.        , 0.98304136],
       [0.98304136, 1.        ]])

### Q.NO.64

In [114]:
mat1 = np.random.randint(1,6,(2,3))
mat2 = np.random.randint(1,6,(3,4))

mat1

array([[3, 4, 5],
       [2, 5, 3]])

In [115]:
mat2

array([[1, 3, 5, 5],
       [4, 3, 3, 2],
       [4, 4, 4, 2]])

In [116]:
np.dot(mat1 , mat2)

array([[39, 41, 47, 33],
       [34, 33, 37, 26]])

### Q.No.65

In [117]:
arr = np.random.randint(10,1000 , size = 50)
print("array is :" ,arr)
      
      
arr1 = np.sort(arr)


print ("sorted array is : ",arr1)

array is : [173 505 873 667 541 929 367 683 208 475 795 458 290 166 585 707 807 269
 865 281 849 920  10 550 822 886 924 630 271 560 262 563 394 532 394  21
 600 394 847 365 528 461 754 257 996 494 445 260 855  77]
sorted array is :  [ 10  21  77 166 173 208 257 260 262 269 271 281 290 365 367 394 394 394
 445 458 461 475 494 505 528 532 541 550 560 563 585 600 630 667 683 707
 754 795 807 822 847 849 855 865 873 886 920 924 929 996]


In [118]:
percentiles = np.percentile(arr, [10, 50, 90])
percentiles

array([204.5, 530. , 874.3])

In [119]:
frst_quartile = np.percentile(arr , 25)
frst_quartile

308.75

In [120]:
third_quartile = np.percentile(arr , 75)
third_quartile

784.75

### Q.No.66

In [121]:
arr = np.array([ 1 , 2 , 34 , 5 , 6 , 78 , 94])
arr

array([ 1,  2, 34,  5,  6, 78, 94])

In [122]:
np.where(arr==78)## .where is used to get the element index where the condition satisfies

(array([5]),)

### Q.NO.67

In [123]:
arr = np.random.randint(2,9 , (1,5))
arr

array([[2, 4, 4, 4, 2]])

In [124]:
sorted_array = np.sort(arr)
sorted_array                ## sorted array in ascending order

array([[2, 2, 4, 4, 4]])

### Q.No.68

In [125]:
arr = np.array([ 12 , 25 , 6 , 42 , 8 , 30 ])

greater_20 = arr[arr>20]   ## filtered the elements greater than 20

greater_20

array([25, 42, 30])

### Q.No.69

In [126]:
arr = np.array ([ 1 , 5 , 8 , 12 , 15 ])

arr1 = arr[arr %3 == 0]   ## here we have used modulo to check the divisibility by 3
arr1

array([12, 15])

### Q.NO.70

In [127]:
arr = np.array([10,20,30,40,50])

more_20 = arr[arr>=20]

more_20   ## first we have filter the elements greater than or equal to 20

array([20, 30, 40, 50])

In [128]:
final = more_20[more_20 <= 40]
final   ## final array contains the elements which are greater than or equal to 20 and less than or eqaul to 40

array([20, 30, 40])

### Q.NO.71

In [129]:
arr = np.array([1,2,3])

arr.dtype

dtype('int64')

### Q.NO. 72

In [130]:
arr = np.array([1,2,3] , dtype = np.int32)

arr.byteswap()


array([16777216, 33554432, 50331648], dtype=int32)

### Q.NO.73

In [131]:
arr = np.array([1,2,3] , dtype = np.int32)

arr1 = arr.newbyteorder()

print("the original array is : ", arr )
print(" the swapped array is : " ,arr1)

the original array is :  [1 2 3]
 the swapped array is :  [16777216 33554432 50331648]


### Q.NO.74

In [132]:
arr = np.array([1,2,3] , dtype = np.int32)

if arr.dtype.byteorder != '=': 
   
    ## swap byte order on based on endianness
    arr_swapped = arr.newbyteorder()

else:
    arr_swapped = arr.copy()

print("the array after byte swapping is :",arr_swapped)

the array after byte swapping is : [1 2 3]


### Q.NO.75

In [133]:
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
byte_swapping_needed = arr.dtype.byteorder != '='

# if byteorder is != '='
if byte_swapping_needed:
    print("Byte swapping is necessary for the current system.")
# if byteorder is '='
else:  
    print("Byte swapping is not necessary for the current system.")


Byte swapping is not necessary for the current system.


### Q.NO. 76

In [134]:
arr1 = np.random.randint(1,10 ,(3,4))
arr1

array([[3, 5, 5, 5],
       [2, 3, 2, 8],
       [5, 8, 6, 3]])

In [135]:
copy_arr = arr1.copy()  ## here we have done copy of arr1
copy_arr

array([[3, 5, 5, 5],
       [2, 3, 2, 8],
       [5, 8, 6, 3]])

In [136]:
copy_arr[1][2] = 3   ## we have modified an element in copies array
copy_arr

array([[3, 5, 5, 5],
       [2, 3, 3, 8],
       [5, 8, 6, 3]])

In [137]:
arr1                 ## we have noticed that there is no change in the arr1

array([[3, 5, 5, 5],
       [2, 3, 2, 8],
       [5, 8, 6, 3]])

### Q.NO.77

In [138]:
matrix = np.random.randint(1,5,(3,3))    ## creating a random array of shape (3,3)
matrix

array([[2, 2, 3],
       [1, 1, 4],
       [4, 4, 2]])

In [139]:
matrix.ndim     ## checking the dimension of matrix

2

In [140]:
view_slice = matrix[1: , :2]     ## slicing the matrix
view_slice

array([[1, 1],
       [4, 4]])

In [141]:
matrix       ## we can observe that there is no change in original matrix

array([[2, 2, 3],
       [1, 1, 4],
       [4, 4, 2]])

### Q.NO.78

In [142]:
array_a = np.arange(1,13)              ## using arange to get a sequential array_a
array_a = array_a.reshape(4,3)         ##reshaping the array_a
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [143]:
view_b = array_a[0:3 , 0:2]   ## slicing of array
view_b

array([[1, 2],
       [4, 5],
       [7, 8]])

In [144]:
view_b + 5     ## broadcasting of addition of 5

array([[ 6,  7],
       [ 9, 10],
       [12, 13]])

In [145]:
array_a         ## there is no alteration in array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Q.NO. 79

In [146]:
orig_array = np.random.randint(1,8,(2,4))
orig_array

array([[7, 6, 6, 7],
       [3, 2, 5, 1]])

In [147]:
reshaped_view = orig_array.reshape(4,2)     ## reshaped the array
reshaped_view

array([[7, 6],
       [6, 7],
       [3, 2],
       [5, 1]])

In [148]:
reshaped_view[1][1] = 8      ## modified an element of 2nd row 2nd element
reshaped_view   

array([[7, 6],
       [6, 8],
       [3, 2],
       [5, 1]])

In [149]:
orig_array       ## here we can see that it reflects change in the original array

array([[7, 6, 6, 8],
       [3, 2, 5, 1]])

### Q.NO. 80

Create a NumPy array 'data' of shape (3,4) with random integers. Extract a copy 'data_copy' of elements greater than 5. Modify an element in 'data_copy' and verify i it affects the original 'data'

In [150]:
data = np.random.randint(1,8,(3,4))
data

array([[4, 1, 6, 3],
       [1, 1, 6, 6],
       [7, 5, 1, 2]])

In [151]:
data_copy = data[data>5]      ## elements greater than 5 in array 'data'
data_copy                  

array([6, 6, 6, 7])

In [152]:
data_copy[3] = 8       ## modifying 4th element as 8
data_copy

array([6, 6, 6, 8])

In [153]:
data       ## here we can see that there is no affect on the original array

array([[4, 1, 6, 3],
       [1, 1, 6, 6],
       [7, 5, 1, 2]])

### Q.NO.81

In [154]:
mat1 = np.random.randint(1,7,(4,4))
mat2 = np.random.randint(1,7,(4,4))

In [155]:
mat1

array([[2, 3, 2, 3],
       [2, 5, 5, 4],
       [5, 5, 2, 4],
       [6, 5, 4, 4]])

In [156]:
mat2

array([[2, 2, 2, 2],
       [6, 3, 3, 2],
       [4, 6, 3, 4],
       [2, 2, 4, 1]])

In [157]:
mat1 + mat2      ## addition og 2 matrices

array([[ 4,  5,  4,  5],
       [ 8,  8,  8,  6],
       [ 9, 11,  5,  8],
       [ 8,  7,  8,  5]])

In [158]:
mat1 - mat2         ## subtraction of 2 matrices

array([[ 0,  1,  0,  1],
       [-4,  2,  2,  2],
       [ 1, -1, -1,  0],
       [ 4,  3,  0,  3]])

### Q.NO.82

In [159]:
C = np.random.randint(1,6,(3,2))
D = np.random.randint(1,6,(2,4))

In [160]:
C       ## matrix of 3X2

array([[5, 5],
       [3, 1],
       [3, 2]])

In [161]:
D      ## matrix of 2X4

array([[4, 1, 1, 1],
       [2, 5, 4, 2]])

In [162]:
C@D         ## matrix multiplication

array([[30, 30, 25, 15],
       [14,  8,  7,  5],
       [16, 13, 11,  7]])

### Q.NO. 83

In [163]:
E = np.random.randint(1,5,(4,5))
E

array([[2, 3, 3, 2, 4],
       [1, 2, 1, 2, 2],
       [2, 2, 3, 4, 2],
       [1, 3, 1, 1, 3]])

In [164]:
E.T  ## transpose of matrix E

array([[2, 1, 2, 1],
       [3, 2, 2, 3],
       [3, 1, 3, 1],
       [2, 2, 4, 1],
       [4, 2, 2, 3]])

### Q.NO. 84

In [165]:
F = np.random.randint(1,5 ,(4,4))
F

array([[2, 4, 3, 3],
       [3, 1, 1, 3],
       [3, 2, 3, 3],
       [1, 1, 1, 1]])

In [166]:
np.linalg.det(F)         ## determinant of matrix F

1.999999999999999

### Q.NO.85

In [167]:
G = np.random.randint(1,10,(3,3))

In [168]:
G

array([[2, 3, 8],
       [9, 5, 8],
       [2, 6, 8]])

In [169]:
np.linalg.inv(G)         ## inverse of matrix G

array([[-4.76190476e-02,  1.42857143e-01, -9.52380952e-02],
       [-3.33333333e-01,  1.13545537e-17,  3.33333333e-01],
       [ 2.61904762e-01, -3.57142857e-02, -1.01190476e-01]])